---
title: 'Comparing interventions'
teaching: 45 # teaching time in minutes
exercises: 30 # exercise time in minutes

---

```{r setup, echo= FALSE}
library(epidemics);library(ggplot2)
```

:::::::::::::::::::::::::::::::::::::: questions 

- How can I quantify the effect of an intervention?


::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand how to compare intervention scenarios against counter factual scenarios

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: prereq

## Prerequisites
+ Complete tutorials 'Simulating transmission' and 'Modelling interventions'

This tutorial has the following concept dependencies:

**Outbreak response** : Intervention types.
:::::::::::::::::::::::::::::::::


## Introduction

To quantify the effect of the intervention we need to compare our intervention scenario to a counter factual scenario. The *counter factual* is the scenario in which nothing changes, often referred to as the 'do nothing' scenario. The counter factual scenario may include no interventions, or if we are investigating the potential impact of an additional intervention in the later stages of an outbreak there may be existing interventions in place. 

## Comparing scenarios

*Coming soon*


## RIVM Vacamole model

*Coming soon*


## Challenge

*Coming soon*

<!-- ::::::::::::::::::::::::::::::::::::: challenge -->

<!-- ## The effect of vaccination on COVID-19 hospitalisations   -->



<!-- ::::::::::::::::: hint -->

<!-- ### HINT -->


<!-- :::::::::::::::::::::: -->


<!-- ::::::::::::::::: solution -->

<!-- ### SOLUTION -->





<!-- ::::::::::::::::::::::::::: -->


<!-- :::::::::::::::::::::::::::::::::::::::::::::::: -->



::::::::::::::::::::::::::::::::::::: keypoints 

- The counter factual scenario must be defined to make comparisons

::::::::::::::::::::::::::::::::::::::::::::::::

