Welcome!

- A reminder of our [Code of Conduct](https://github.com/epiverse-trace/.github/blob/main/CODE_OF_CONDUCT.md). If you experience or witness unacceptable behaviour, or have any other concerns, please notify the course organisers or host of the event. To report an issue involving one of the organisers, please use the [LSHTM’s Report and Support tool](https://reportandsupport.lshtm.ac.uk/).

| **Roll call** (Confirm you can edit) |
|---|
| - Your name + Find an emoji writing only a double-colon “**:**” |

# Read This First

<!-- visible for learners and instructors at practical -->

Instructions:

- Each `Activity` has five sections: the Goal, Questions, Steps, Inputs, and Your Answers.
- Solve each Activity in the corresponding `.R` file mentioned in the `Steps` section.
- Paste your figure and table outputs and write your answer to the questions in the section `Your Answers`.
- Choose one room member to share your room's results with the rest of the participants.

| **Room** | **Write the room member names** |
|---|---|
| 1 |  |
| 2 |  |
| 3 |  |
| 4 |  |

Remember:

During the practical, instead of simply copying and pasting, we encourage learners to increase their fluency in writing R by using:

- **The double-colon notation**, e.g. `package::function()`, to specify which package a function comes from, avoid namespace conflicts, and find functions using keywords.
- **Tab key <kbd>↹</kbd>** 
to [autocomplete package or function names](https://support.posit.co/hc/en-us/articles/205273297-Code-Completion-in-the-RStudio-IDE) and [display possible arguments](https://docs.posit.co/ide/user/ide/guide/code/console.html).
- [**R shortcuts**](https://positron.posit.co/keyboard-shortcuts.html#r-shortcuts) to 
    - Insert the pipe operator (`%>%`) using `Ctrl/Cmd`+`Shift`+`M`, 
    - Insert the assignment operator (`<-`) using `Alt/Option`+`-`, and 
    - [Execute one line of code](https://docs.posit.co/ide/user/ide/guide/code/execution.html) or multiple lines connected by the pipe operator (`%>%`) by placing the cursor in the code of interest and pressing `Ctrl`+`Enter`.
- **The `help()` function** or `?` operator to access the [function reference manual](https://www.r-project.org/help.html).

If your local configuration was not possible to set up:

- Create one copy of the [Posit Cloud RStudio project](https://posit.cloud/content/10566863).

<!-- - Create one copy of the [Posit Cloud RStudio project](https://posit.cloud/spaces/609790/join?access_code=hPM1tIeKt5ax_Y-P0lMGVUGqzFPNH4wxkKSzXZYb). -->

## Paste your !Error messages here

Participants, if you get an unexpected message in the console. Copy and paste it into this section.

```







```